
title: Meu Blog Tech Autônomo
description: Blog técnico automatizado sobre tecnologia, backend e IA.
url: https://bernardipp-d.github.io/techmanIAco
baseurl: ""
theme: minima
plugins:
  - jekyll-seo-tag
markdown: kramdown
